[package]
name = "wasm_interface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lib_raytracer = { path = "../lib_raytracer" }
nalgebra-glm = "0.15"
num-traits = "0.2"
wasm-bindgen = "0.2.78"
# TODO: Use panic handler to console
# Todo: Maybe use Wee-Alloc

